mkdir data
cd data
wget https://stacks.stanford.edu/file/druid:py883nd2578/VT-clean.csv.gz
wget https://stacks.stanford.edu/file/druid:py883nd2578/MA-clean.csv.gz
wget https://stacks.stanford.edu/file/druid:py883nd2578/CT-clean.csv.gz
wget https://stacks.stanford.edu/file/druid:py883nd2578/WI-clean.csv.gz
wget https://stacks.stanford.edu/file/druid:py883nd2578/AZ-clean.csv.gz
wget https://stacks.stanford.edu/file/druid:py883nd2578/CO-clean.csv.gz
wget https://stacks.stanford.edu/file/druid:py883nd2578/NC-clean.csv.gz
wget https://stacks.stanford.edu/file/druid:py883nd2578/WA-clean.csv.gz
wget https://stacks.stanford.edu/file/druid:py883nd2578/TX-clean.csv.gz